spring.application.name=parking-control
# ================================
# CONEXÃO COM POSTGRESQL
# ================================
spring.datasource.url=jdbc:postgresql://localhost:5432/parkingtest
spring.datasource.username=postgres
# spring.datasource.password=123456
# ================================
# JPA / HIBERNATE
# ================================
# ou 'create', 'validate', 'none'
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lab.non_contexual_creation=true

# Exibe queries no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true